[service]
host = "0.0.0.0:80"

[database]
username = "postgres"
password = "postgres"
port = "5432"
database_name = "zero2prod"

[email_client]
base_url = "https://example.com"
sender = "email@example.com"
auth_token = "my-secret-token"
timeout_seconds = 10
