[database]
username = "postgres"
password = "postgres"
host = "127.0.0.1"
port = "5432"
database_name = "zero2prod"

[email_client]
base_url = "https://example.com"
sender = "email@example.com"
auth_token = "my-secret-token"
timeout_seconds = 10
